export const employeesList = [
  {
    id: 1,
    firstName: "François",
    lastName: "Durand",
    startDate: "01/01/2025",
    department: "Sales",
    birthDate: "01/01/1990",
    street: "3 rue de la tour",
    city: "Lyon",
    state: "Alaska",
    zipCode: "10569",
  },
  {
    id: 2,
    firstName: "Albert",
    lastName: "Einstein",
    startDate: "01/01/2024",
    department: "Human Resources",
    birthDate: "01/01/1990",
    street: "5 avenue du port",
    city: "Lyon",
    state: "Colorado",
    zipCode: "45665",
  },
  {
    id: 3,
    firstName: "Fordon",
    lastName: "Saquet",
    startDate: "02/01/2025",
    department: "Sales",
    birthDate: "01/01/1990",
    street: "6 boulevard du vin",
    city: "Lyon",
    state: "Colorado",
    zipCode: "74564",
  },
  {
    id: 4,
    firstName: "Amina",
    lastName: "Tou",
    startDate: "10/02/2025",
    department: "Legal",
    birthDate: "01/01/1990",
    street: "456 rue des fleurs",
    city: "Nantes",
    state: "California",
    zipCode: "41355",
  },
  {
    id: 5,
    firstName: "Sabrina",
    lastName: "Turpin",
    startDate: "03/01/2025",
    department: "Sales",
    birthDate: "01/01/1990",
    street: "546 avenue bonbon",
    city: "Lyon",
    state: "Colorado",
    zipCode: "45441",
  },
  {
    id: 6,
    firstName: "Jacques",
    lastName: "Chirac",
    startDate: "01/04/2025",
    department: "Connecticut",
    birthDate: "01/01/1990",
    street: "5 rue froide",
    city: "Paris",
    state: "California",
    zipCode: "45354",
  },
  {
    id: 7,
    firstName: "Pedro",
    lastName: "Dos Santos",
    startDate: "02/03/2025",
    department: "Legal",
    birthDate: "01/01/1990",
    street: "2 rue des Basses Barolles",
    city: "Saint Genis Laval",
    state: "California",
    zipCode: "45564",
  },
  {
    id: 8,
    firstName: "Kylian",
    lastName: "M'Bapé",
    startDate: "01/02/2025",
    department: "Marketing",
    birthDate: "01/01/1990",
    street: "rue du stade de France",
    city: "Marseille",
    state: "Alaska",
    zipCode: "46584",
  },
];
