import { combineReducers, configureStore } from "@reduxjs/toolkit";
import { employeeSlice } from "./slices/employeeSlice";

let state = {
  employees: [
    {
      id: 1,
      firstName: "toto",
      lastName: "Durand",
      startDate: "01/01/2025",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Lyon",
      state: "toto",
      zipCode: "toto",
    },
    {
      id: 2,
      firstName: "toto",
      lastName: "toto",
      startDate: "01/01/2024",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Lyon",
      state: "toto",
      zipCode: "toto",
    },
    {
      id: 3,
      firstName: "toto",
      lastName: "toto",
      startDate: "02/01/2025",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Lyon",
      state: "toto",
      zipCode: "toto",
    },
    {
      id: 4,
      firstName: "toto",
      lastName: "toto",
      startDate: "10/02/2025",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Nantes",
      state: "toto",
      zipCode: "toto",
    },
    {
      id: 5,
      firstName: "toto",
      lastName: "toto",
      startDate: "03/01/2025",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Lyon",
      state: "toto",
      zipCode: "toto",
    },
    {
      id: 6,
      firstName: "toto",
      lastName: "toto",
      startDate: "01/04/2025",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Paris",
      state: "toto",
      zipCode: "toto",
    },
    {
      id: 7,
      firstName: "toto",
      lastName: "toto",
      startDate: "02/03/2025",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Paris",
      state: "toto",
      zipCode: "toto",
    },
    {
      id: 8,
      firstName: "toto",
      lastName: "toto",
      startDate: "01/02/2025",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Marseille",
      state: "toto",
      zipCode: "toto",
    },
    {
      id: 9,
      firstName: "toto",
      lastName: "gateau",
      startDate: "03/02/2025",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Lyon",
      state: "toto",
      zipCode: "toto",
    },
    {
      id: 10,
      firstName: "toto",
      lastName: "toto",
      startDate: "01/03/2025",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Paris",
      state: "toto",
      zipCode: "toto",
    },
    {
      id: 11,
      firstName: "toto",
      lastName: "toto",
      startDate: "02/02/2025",
      department: "toto",
      birthDate: "01/01/1990",
      street: "toto",
      city: "Paris",
      state: "toto",
      zipCode: "toto",
    },
  ],
};

export const store = configureStore({
  preloadedState: state,
  reducer: combineReducers({ employees: employeeSlice.reducer }),
});
